### ISSUE TITLE
Calendar - to add Start/End when click JO

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#1]
Hi MMS - can u add the actual start and end button in this page? So it would be easier for the tech staff going on site to customer’s place. Thanks

This is in the Calendar when i clicked on the JO (view from Mobile)
<img width="928" alt="2019-03-17_10h32_13" src="https://user-images.githubusercontent.com/47963293/54484359-14a78180-48a0-11e9-9303-09b771968894.png">

**Comment by mmms-uniqe** [comment]
i'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, ok.
