### ISSUE TITLE
Job order creation - Activity Type display (to sort by description)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#10]
Job order creation - Activity Type display (to sort by description)
- currently, the sorting is by Activity Type code. Please change sort by Type Description.
![2019-03-18_13h27_23](https://user-images.githubusercontent.com/47963293/54508997-eea6dd80-4982-11e9-9eee-a4b2a11a6962.png)

**Comment by ErwinMetra** [comment]
Also, pls do not show **Inactive** Activity Types

**Comment by mmms-uniqe** [comment]
i'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, ok, nicely sorted.
