### ISSUE TITLE
Settings - Activity Type

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#11]
Settings - Activity Type
Request: Sort this by **Activities Desc**
![2019-03-18_14h37_16](https://user-images.githubusercontent.com/47963293/54511279-70026e00-498b-11e9-971c-52db6e93c11a.png)

**Comment by mmms-uniqe** [comment]
i'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, ok, nice.
