### ISSUE TITLE
Creation of JO - filter Tickets

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#2]
Pls limit the Select Ticket list to the tickets under the Project Name....Currently, it shows ALL ticket numbers for all projects.
<img width="611" alt="2019-03-17_10h36_12" src="https://user-images.githubusercontent.com/47963293/54484376-87186180-48a0-11e9-8513-57091e2feb6d.png">

**Comment by mmms-uniqe** [comment]
i'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, the filter of ticket is working.
