### ISSUE TITLE
JO creation - Assigned To selection field

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#3]
Issue on Creating JO even if the staff is not a Team Member

<img width="960" alt="2019-03-17_10h39_01" src="https://user-images.githubusercontent.com/47963293/54484405-06a63080-48a1-11e9-8ee7-d43bc2e087db.png">

**Comment by mmms-uniqe** [comment]
i'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, the filter is only showing team members assigned to the project.
