### ISSUE TITLE
Project creation - 

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#4]
when creating a new project, pls do not show those users that were Banned in the Assigned To field

<img width="617" alt="2019-03-17_10h42_19" src="https://user-images.githubusercontent.com/47963293/54484421-643a7d00-48a1-11e9-9631-ecab68c00e4b.png">

**Comment by mmms-uniqe** [comment]
I'v finished this issue.

**Comment by ErwinMetra** [comment]
Now, OK.
