### ISSUE TITLE
Job Order creation - new field for Activity Type

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/Job-Order-PMS#5]
hi MMS - pls insert Activity Type selection in the Job Order creation... This activity Type can be selected in the ticket. The smallest unit is JO and each JO should have a Activity Type. This Activity Type will be used later on when we generate report for Tech Staffs commission calculation.

**Comment by mmms-uniqe** [comment]
i'v finished this issue

**Comment by ErwinMetra** [comment]
The activity type can now be selected when creating a new JO. Thanks,
